# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MostUsedToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50, null=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='TokenAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True, verbose_name='Amount')),
                ('token', models.CharField(max_length=50, null=True, verbose_name='Token')),
                ('MostUsedToken', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='keywords.MostUsedToken')),
            ],
        ),
    ]
