# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_commentnegtoken_negtokenscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPosToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50, null=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='PosTokenScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(null=True, verbose_name='Score')),
                ('token', models.CharField(max_length=50, null=True, verbose_name='Token')),
                ('CommentPosToken', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='keywords.CommentPosToken')),
            ],
        ),
    ]
