# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-25 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpBased',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.TextField(null=True, verbose_name='Friend')),
                ('user', models.CharField(max_length=50, null=True, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='TimeBased',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.TextField(null=True, verbose_name='Friend')),
                ('user', models.CharField(max_length=50, null=True, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='UserFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.TextField(null=True, verbose_name='Freq')),
                ('user', models.CharField(max_length=50, null=True, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fans', models.TextField(null=True, verbose_name='Fans')),
                ('user', models.CharField(max_length=50, null=True, verbose_name='User')),
            ],
        ),
    ]
