# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-02 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_query', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.TextField(null=True, verbose_name='Graph')),
                ('user', models.CharField(max_length=50, null=True, verbose_name='User')),
            ],
        ),
    ]
