# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-02 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('id_query', '0002_usergraph'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGraph',
        ),
    ]
