# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('id_query', '0003_delete_usergraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, null=True, verbose_name='Content')),
                ('score', models.IntegerField(null=True, verbose_name='Score')),
                ('user', models.CharField(max_length=50, null=True, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Title')),
                ('date', models.CharField(max_length=50, null=True, verbose_name='Date')),
                ('url', models.CharField(max_length=50, null=True, verbose_name='Url')),
                ('author', models.CharField(max_length=50, null=True, verbose_name='Author')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='id_query.Comment')),
            ],
        ),
    ]
