# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_query', '0008_graph_link_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='graph',
        ),
        migrations.RemoveField(
            model_name='node',
            name='graph',
        ),
        migrations.AddField(
            model_name='link',
            name='graphs',
            field=models.ManyToManyField(to='id_query.Graph'),
        ),
        migrations.AddField(
            model_name='node',
            name='graphs',
            field=models.ManyToManyField(to='id_query.Graph'),
        ),
    ]
