# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_query', '0010_auto_20161215_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, null=True, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(null=True, verbose_name='Source')),
                ('target', models.IntegerField(null=True, verbose_name='Target')),
                ('total_comment', models.IntegerField(null=True, verbose_name='Total_comment')),
                ('fan_comment', models.IntegerField(null=True, verbose_name='Fan_comment')),
                ('comment_rate', models.FloatField(null=True, verbose_name='Comment_rate')),
                ('width', models.FloatField(null=True, verbose_name='Width')),
                ('value', models.IntegerField(null=True, verbose_name='Value')),
                ('graphs', models.ManyToManyField(to='id_query.Graph')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField(null=True, verbose_name='Group')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('graphs', models.ManyToManyField(to='id_query.Graph')),
            ],
        ),
    ]
